#!/usr/bin/env bash
# displays numbers from 1-100, "FizzBuzz" when number is a multiple of 3 and 5. 
#Displays "Fizz" if number is a multiple of 3,"Buzz" if number is multiple of 5,
#otherwise displays the numb in list fmt

z=1

while [ $z -le 100 ]
do
	if [ $((z % 3)) -eq 0 -a $(( z % 5 )) -eq 0 ] 
	then
		echo "FizzBuzz"
	elif [ $(( z % 5 )) -eq 0 ]
	then
		echo "Buzz"
	elif [ $(( z % 3 )) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$z"
	fi
	z=$(( z + 1 ))
done
