#!/usr/bin/env bash
#Looping using the "until loop" to print/display Best School 10 times on 10 lines.
count=0
until false
do
	((count++))
	if [[ $count -eq 10 ]]
	then
		break
	fi
	echo "Best School"
done
