#!/usr/bin/env bash
# script will display Best School 10x , the 9th iteration displays Best School then hi on new line
z=1

while [ $z -le 10 ]
do
	echo "Best School"
	if [ $z -eq 9 ]

		echo "Hi"
	fi
	z=$(( z + 1 ))
done
