#!/usr/bin/env bash
# script loops 1-10 and 4th loop says bad luck , 8th good luck, all other loops "Best School"
z=1
while [ $z -le 10 ]
do
	if [ $z -eq 4 ]
	then
		echo "bad luck"
	elif [ $z -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	z=$(( z+1 ))
done
