#!/usr/bin/env bash
# script displays 1-20, on 4 bad luck from china, 9 bad luck from japan, 17 bad luck from Italy.
z=1
while [ $z -le 20 ] 
do
	echo $z
	case $z in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	z=$(( z + 1 ))
done
