#!/usr/bin/env bash
# displays info about the school file

filename="School"
if [ -e $filename ]
then
echo "School file exist"
if [ -s $filename ]
then
echo "School file is not empty"
else
echo "School file is empty"
fi
if [ -f $filename ]
then
echo "School is a regular file"
fi
else
echo "school file does not exist"
fi
